[pytest]
addopts = -p no:cacheprovider -p no:warnings -p no:terminalreporter
filterwarnings =
    ignore::DeprecationWarning:fastapi\.routing
    ignore::DeprecationWarning:starlette\._utils
    ignore:.*WindowsSelectorEventLoopPolicy.*:DeprecationWarning
    ignore:.*set_event_loop_policy.*:DeprecationWarning
